//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationExampleProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamer
    {
        public int Id { get; set; }
        public string Player { get; set; }
        public Nullable<int> GameId { get; set; }
        public string Score { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
